# Generated by Django 4.0.4 on 2023-01-23 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_que_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Course_status', models.BooleanField(default=False)),
                ('Course_createdAt', models.DateField(default=datetime.datetime(2023, 1, 23, 12, 24, 19, 478901))),
            ],
        ),
    ]
