# Generated by Django 4.1.2 on 2023-01-23 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_courses_course_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_createdAt',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 17, 35, 36, 438487)),
        ),
    ]
