# Generated by Django 4.1.2 on 2023-01-23 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_projectname_evaluations_projectname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_createdAt',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 17, 51, 19, 240859)),
        ),
    ]
